"""phone_number

Revision ID: 4ba804ec05f2
Revises: 3dbaf9e49e6e
Create Date: 2023-02-24 13:22:28.491769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba804ec05f2'
down_revision = '3dbaf9e49e6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_No', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_No')
    # ### end Alembic commands ###
