"""phone_number2

Revision ID: 6851d69847a2
Revises: 4ba804ec05f2
Create Date: 2023-02-24 13:23:51.283875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6851d69847a2'
down_revision = '4ba804ec05f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.drop_column('users', 'phone_No')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_No', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
